### ISSUE TITLE
Corrección Proyecto. Fase: UT2. Casos de Uso

### ISSUE THREAD

**Issue by jlr2** [Ctrusan/proyectopsp-grupo4#4]
**Ortografía** 
precondición, excepciones, postcondición       **REVISION: NO realizado**

**Diagrama de CU**

- [x] Según vuestro diagrama de CU cuando un usuario (alumno o profesor) inicia una sesión tiene accesibles todas las funcionales recogidas en el resto de CUs. Es verdad, que en cada caso de uso indicáis que el rol que debe cumpir, alumno o profesor, pero según el diagrama tanto si un usuario se autentica como alumno o como profesor tendrá accesible todas las funcionalidades. Sería más recomendable no poner un actor "usuario" del que heredan los actores "Alumno" y "Profesor", sino poner cada actor, alumno y profesor, como una relación con "Iniciar Sesión" que tiene extensiones con los CUs específicos de cada rol.    **REVISION: habéis eliminado el actor Usuario del que heredaban Alumno y Profesor; bien hecho, pero cada actor no tiene porqué iniciar sesión para acceder a sus funcionalidades.**
- [x] No crucéis las líneas; mejor si ponemos el mismo actor en otra parte del diagrama.  **REVISION: SÍ realizado**
- [x] No se ven las puntas de flecha de las relaciones extends.  **REVISION: SÍ realizado**

**CU Iniciar Sesión**
- [x] Precondición: ¿cómo puede tener un usuario una cuenta creada? No veo ese CU.  **REVISION: NO realizado**
- [x] Curso normal:
    - Indicar los pasos en diferentes líneas. Misma corrección en otros CUs. **REVISION: SÍ realizado**
     - Detallar el diálogo entre los actores y el sistema. Si indicáis que se debe introducir el nombre de usuario y contraseña, es porque el sistema debe haberlo pedido antes.  Esto general para cualquier caso de uso, hay que detallar la información que fluje indicando los pasos.  **REVISION: NO realizado**
     - Según vuestro diagrama hay relaciones Extends con varios CUs. El curso normal no lo recoge (Punto de Extensión: título de cada CU). **REVISION: NO realizado**
 - [x] Alternativas: hay que relacionar el número de paso con el número de paso en el curso normal.  **REVISION: NO realizado**

**CU Enviar y Consultar**
- [x] Nombre: este nombre de CU no aparece en el diagrama  **REVISION: NO realizado**
- [x] Curso normal:
   -  Sobra decir iniciar sesión como alumno ya que se ha indicado en la precondición. **REVISION: SÍ realizado**
   -  Los pasos 2 y 3 se resumen en uno: seleccionar "enviar dudas y consultar". **REVISION: SÍ realizado**
   -   Falta indicar que el alumno envía la duda.   **REVISION: SÍ realizado**
- [x] Alternativa: mismo comentario anterior.  **REVISION: NO realizado**

**CU consultar y responder dudas**
- [x] Curso normal: mismos comentarios a CU anterior. **REVISION: SÍ realizado**
- [x] Alternativa: mismos comentarios  a CU anterior. **REVISION: NO realizado**

**CU Ver tareas más próximas**
- [x] Actores: según el diagrama PARECE que sólo es el alumno.   **REVISION: SÍ realizado**
- [x] Curso normal:
   - Mismos comentarios  a CU anterior.    **REVISION: SÍ realizado**
   - Detallar la información que muestra el sistema. Esto permitirá tener la información requerida para el diseño (modelo er + diagrama de clases).   **REVISION: SÍ realizado**
- [x] Alternativa: mismos comentarios  a CU anterior.   **REVISION: NO realizado**

**CU Enviar Notificaciones**    **REVISION: lo habéis eliminado**
- [x] Curso normal: mismos comentarios a CU anterior.
- [x] Alternativas: mismos comentarios  a CU anterior.

**CU Leer Calendario**
- [x] Actores: parece que el único es Alumno según el diagrama. La solución pasa por el comentario que realizada en "Diagrama de CU".     **REVISION: SÍ realizado**
- [x] Curso normal: mismos comentarios a CU anterior.  Detallar más la información que fluye.   **REVISION: SÍ realizado**
- [x] Alternativas: mismos comentarios  a CU anterior.   **REVISION: NO realizado**

**CU Modificar Calendario**
Nombre: el nombre en el diagrama es diferente.    **REVISION: NO realizado**
 - [x] Actores:  Según el diagrama puede entenderse que también lo es el alumno. La solución pasa por el comentario que realizada en "Diagrama de CU".    **REVISION: SÍ realizado**
- [x] Curso normal: mismos comentarios a CU anterior.  Detallar más la información que fluye y la interacción actor-sistema.   **REVISION: NO realizado**
- [x] Alternativas: mismos comentarios  a CU anterior.  **REVISION: NO realizado**

**CU Crear Calendario**
 - [x] Actores:  mismo comentario  a CU anterior.  **REVISION: SÍ realizado**
- [x] Curso normal: mismos comentarios a CU anterior.  Detallar más la información que fluye y la interacción actor-sistema.  **REVISION: NO realizado**
- [x] Alternativas: mismos comentarios  a CU anterior.  **REVISION: NO realizado**

**Comment by JosePalacios56** [comment]
En el caso de uso de Iniciar Sesión no se podrán crear nuevos usuarios, ya vendrá con una base de datos predeterminada con las cuentas ya creadas.
